#!/bin/sh

set -e
CURRENT_SHA=$(git rev-parse --short HEAD)

# watch for workflow run to complete then download firmware
# TODO more robust workflow selection
gh run watch --exit-status && \
    gh run download -D firmware/$CURRENT_SHA -n firmware

# go to firmware download directory
cd firmware/$CURRENT_SHA

if [ ! -f corneish_zen_v2_right-zmk.uf2 ] || [ ! -f corneish_zen_v2_left-zmk.uf2 ]
then
    echo "Can't find firmware files!"
    exit 1
fi

trap 'exit 1' 2

echo "Please connect the $(tput bold)left$(tput sgr0) half.\nWaiting for Zen to connect\c"
while [ ! -d /Volumes/CORNEISHZEN ]
do
    echo '.\c'
    sleep 1
done
sleep 1
cp corneish_zen_v2_left-zmk.uf2 /Volumes/CORNEISHZEN/
echo "\n"


while [ -d /Volumes/CORNEISHZEN ]
do
    sleep 1
done

echo "Please connect the $(tput bold)right$(tput sgr0) half.\nWaiting for Zen to connect\c"
while [ ! -d /Volumes/CORNEISHZEN ]
do
    echo '.\c'
    sleep 1
done
sleep 1
cp corneish_zen_v2_right-zmk.uf2 /Volumes/CORNEISHZEN/

echo "\nDone!"
