# on: [push, pull_request, workflow_dispatch]

# jobs:
#   build:
#     uses: LOWPROKB/zmk/.github/workflows/build-user-config.yml@corne-ish-zen-v2

name: Build ZMK firmware
on:
  workflow_dispatch:
  push:
    paths:
      - config/west.yml
      - config/*.keymap
      - config/*.dtsi
      - config/boards/**
      - build.yaml

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
